### ISSUE TITLE
Add ability to load presaved tweets directly into Couchbase and Elasticsearch without needing to have HDP setup

### ISSUE THREAD

**Issue by risdenk** [westeras/hdp-es-cb-demo#21]
Setting up HDP can be a pain and not necessary unless building the whole demo. It would be great to be able to load a snapshot of data into Couchbase and basically use this as a quickstart.

**Comment by westeras** [comment]
With commit 077bb2f36ffbf30e05778768c3e71a8b6e966e61 I added a sample data file, then with f548ae1e6214b9289128ef9ea50e60ce5b3f886f I added instructions to the README explaining how to set up a Couchbase/Elasticsearch environment without spinning up the HDP node, and instructions explaining the bulk import process into Couchbase

**Comment by risdenk** [comment]
@westeras would be nice if the README didn't explicitly say you need to destroy existing machines. The  load of the data could be done on an existing cluster
