### ISSUE TITLE
Kibana won't start when VM is restarted

### ISSUE THREAD

**Issue by westeras** [westeras/hdp-es-cb-demo#28]
If you do this:

``` sh
vagrant halt elasticsearch.demo
vagrant up elasticsearch.demo
```

Kibana won't be running afterwards

**Comment by risdenk** [comment]
This is due to Elasticsearch not being available when Kibana starts. There is no way to know that Kibana will be started after Elasticsearch. The fix for this is:

```
vagrant up elasticsearch.demo
vagrant ssh elasticsearch.demo
sudo service elasticsearch status
# Make sure that elasticsearch is up
sudo service kibana4 start
```

This needs to be added to the README
