### ISSUE TITLE
HDP Installation fails silently and can't be restarted

### ISSUE THREAD

**Issue by westeras** [westeras/hdp-es-cb-demo#40]
Circumstances under which Ambari Blueprints fails to kick off a cluster installation are unclear.  It happens when single-node-mapping.json is posted to http://hdp.demo:8080/api/v1/clusters/.  Once blueprint.py has finished, opening Ambari at http://hdp.demo:8080 will either show cluster installation in progress, or be in a strange state where nothing is happening.

**Comment by westeras** [comment]
@risdenk is this fixed?

**Comment by risdenk** [comment]
Might be mitigated by #35 since there is better error handling now. Close this for now and reopen if there are further problems.
