### ISSUE TITLE
Determine relevancy for the searchapp

### ISSUE THREAD

**Issue by kruthar** [westeras/hdp-es-cb-demo#65]
The searchapp at https://github.com/westeras/hdp-es-cb-demo/tree/master/searchapp, is it still relevant? There is no documentation on how to build, run, or use it. Need to determine if it is still relevant, if so finish it or at least document it so development can be continued later. If not, then it should be removed.

**Comment by risdenk** [comment]
Running the search app:
`mvn clean jetty:run`
Navigate to [http://localhost:8080/index.jsp](http://localhost:8080/index.jsp)

**Comment by kruthar** [comment]
This is to run the search app locally, do you see a need to add provisioning to vagrant for it? If not, I think documenting this in the README should be enough to close this issue.

**Comment by risdenk** [comment]
It might make sense to change the node box to be the webapp box. That could run the searchapp as well?

**Comment by kruthar** [comment]
I like it. :beers:

**Comment by risdenk** [comment]
Based on further evaluation, I found that the searchapp doesn't do anything that the angular version doesn't do. This means that it can be removed. I filed #93 for this.
