### ISSUE TITLE
Clean up elasticsearch-twitter-app

### ISSUE THREAD

**Issue by kruthar** [westeras/hdp-es-cb-demo#67]
Need to remove all files and directories that will be created during npm and bower install steps. There may also be other files that are just generally not necessary, the app dir needs to be strip down to the bare bones of running it, in the pretext that we have automated the npm, bower, and any other installation and start scripts.

**Comment by risdenk** [comment]
> Need to remove all files and directories that will be created during npm and bower install steps.

Is that still the case? Wasn't that handled by updating the .gitignore and removing the files?

> There may also be other files that are just generally not necessary
- view1/view2 should be removed
- what is the `couchbasedemofiles` folder?
- do we need elasticjs and elasticsearchui?
- remove index*.html and rename elasticuidemo.html to index.html

**Comment by risdenk** [comment]
Related to #77

**Comment by risdenk** [comment]
Fixed by #80.
