### ISSUE TITLE
consolidate vagrant artifacts

### ISSUE THREAD

**Issue by kruthar** [westeras/hdp-es-cb-demo#88]
The recent change to reorganize the Vagrant provisioning stuff put all of the vagrant artifacts at the top level of the project. This makes the shared folder include the entire project which is not necessarily desirable. There is also a lot of clutter at the top level with all the vagrant stuff being free.

This can probably be fixed by moving all vagrant artifacts except Vagrantfile to a vagrant/, then specifying vagrant/ as the shared folder instead of the default '.'.

@cricket007 to work on this.

**Comment by OneCricketeer** [comment]
:ok:
